env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
    secure: "HX4Uy/179AB8/hJA6RwTG9uK6kpqBVS525qj9chLNYNtm9w1UP1f2O8oZeRMMehYugmZ+wfo8iYgzJbFpZ3JEKUg/TgnJndtyY4Y6nxhfFXbFwYXUpQilmb+Ek9l7rGnSsaFNSO3O1s49gzWltBIzCW4xEURJn+SIPIK55kqOis="


language: c
addons:
  apt:
    packages:
     - libgmp-dev 
     - linux-kernel-headers
     - build-essential
     - kernel-package
     - libssl-dev 

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "PeterHuewe/tpm-emulator"
      description: "PeterHuewe/tpm-emulator"
    notification_email: peterhuewe@gmx.de
    build_command_prepend:  mkdir -p build && cd build 
    build_command: cmake -DBUILD_DEV=OFF ../ && make
    branch_pattern: coverity_scan

script:  mkdir -p build && cd build && cmake -DBUILD_DEV=OFF ../ && make && cd ..
